### ISSUE TITLE
Cancel button on showCalendarDatePicker2Dialog does not work.

### ISSUE THREAD

**Issue by awazgyawali** [theideasaler/calendar_date_picker2#2]
I am not able to close the dialog using the cancel button.

**Comment by theideasaler** [comment]
Hi @awazgyawali, this is actually the default behaviour - `Cancel` button will only revert the user actions instead of closing the dialog. Because the component wrapped inside dialog is `CalendarDatePicker2WithActionButtons` which could be potentially used anywhere else other than a dialog. This behaviour is to keep the action buttons behaviour consistent across different components.

But since you mentioned it, I think it makes sense that user should have the ability to control the behaviour as well.  So, I have introduced a new config option - `shouldCloseDialogAfterCancelTapped` into `CalendarDatePicker2WithActionButtonsConfig`, you can turn it to `true` to make the button close dialog.
