### ISSUE TITLE
[Feature] dayBuilder should cover selected date in range to customize decoration

### ISSUE THREAD

**Issue by AlexanderBykin** [theideasaler/calendar_date_picker2#217]
**Describe the feature you'd like**
current version 1.1.6 doesn't give a chance to customize container for dates in between selected range, only gives possibility to change highlight color.

**Use cases**
customize decoration selected date cells that is between selected date range, look at attachment.

Attachment
<img width="288" alt="Screenshot 2024-09-04 at 16 36 44" src="https://github.com/user-attachments/assets/c101a331-a3a3-4f2f-b031-35f8b370c09d">

**Comment by theideasaler** [comment]
resolved in https://github.com/theideasaler/calendar_date_picker2/pull/222

**Comment by AlexanderBykin** [comment]
@theideasaler are you sure that **SelectedRangeHighlightBuilder** function arguments is defined with NullSafety rules?
```
/// Function to provide full control over range picker highlight
typedef SelectedRangeHighlightBuilder = Widget Function({
  DateTime dayToBuild, // <-- wrong argument definition
  bool isStartDate, // <-- wrong argument definition
  bool isEndDate, // <-- wrong argument definition
});
```

**Comment by RNOVOSELOV** [comment]
How to use selectedRangeHighlightBuilder?

I receive warnings for each parameter:
The parameter 'dayToBuild' can't have a value of 'null' because of its type, but the implicit default value is 'null'.
The parameter 'isEndDate' can't have a value of 'null' because of its type, but the implicit default value is 'null'.
The parameter 'isStartDate' can't have a value of 'null' because of its type, but the implicit default value is 'null'.
